[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 20000000

remappings = [
	"@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]